#!/usr/bin/perl

use strict;
use warnings;

#
# read in game state
#
my %params;
if (exists $ENV{'QUERY_STRING'}) {
    my @args = split /\&/, $ENV{'QUERY_STRING'};
    foreach my $arg (@args) {
	my @bits = split /=/, $arg;
	next unless (@bits == 2);
	$params{$bits[0]} = $bits[1];
    }
}

if (exists $ENV{'CONTENT_LENGTH'}) {
    my $content = $ENV{'CONTENT_LENGTH'};
    if ($content > 0) {
	my $data = <STDIN>;
	my @args = split /\&/, $data;
	foreach my $arg (@args) {
	    my @bits = split /=/, $arg;
	    next unless (@bits == 2);
	    $params{$bits[0]} = $bits[1];
	}
    }
}

my $game = "";
my $team = "";

$game = $params{'game'} if (defined $params{'game'});
$team = $params{'team'} if (defined $params{'team'});

if ("$game" eq "" || "$team" eq "") {
    print "Content-type: text/html; charset=UTF-8\n\n";
    print "<html lang=\"en\"><head>\n";
    print "    <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n";
    print "    <meta charset=\"utf-8\">\n";
    print "  </head>\n";
    print "  <body>\n";
    print "  <h2>Error, missing venue, match, robot position, and/or team</h2>\n";
    print "  </body></html>\n";
    exit(0);
}

my @gbits  = split /_/, $game;
my $event  = $gbits[0];
my $match  = $gbits[1];
my $posnum = $gbits[2];

my $RED  = "bgcolor=\"#ff6666\"";
my $BLUE = "bgcolor=\"#99ccff\"";

my $color = $RED;
$color = $BLUE if ($posnum > 3);

#print "<!DOCTYPE html>\n";
print "Content-type: text/html; charset=UTF-8\n\n";
print "<html lang=\"en\"><head>\n";
print "    <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n";
print "    <meta charset=\"utf-8\">\n";
print "  </head>\n";
print "  <body>\n";
print "\n";
print "    <script>\n";
print "      var autoLoCount;\n";
print "      var autoHiCount;\n";
print "      var autoBounce;\n";
print "      var autoMissed;\n";
print "      var taxi;\n";
print "      var human;\n";
print "      var teleLoCount;\n";
print "      var teleHiCount;\n";
print "      var teleBounce;\n";
print "      var teleMissed;\n";
print "      var shootWLP;\n";
print "      var shootOLP;\n";
print "      var shootHub;\n";
print "      var shootField;\n";
print "      var rung;\n";
print "      var defense;\n";
print "      var defended;\n";
print "      var fouls;\n";
print "      var techfouls;\n";
print "      var robot;\n";
print "\n";
print "      autoLoCount = 0;\n";
print "      autoHiCount = 0;\n";
print "      autoBounce = 0;\n";
print "      autoMissed = 0;\n";
print "      taxi = 0;\n";
print "      human = 0;\n";
print "      teleLoCount = 0;\n";
print "      teleHiCount = 0;\n";
print "      teleBounce = 0;\n";
print "      teleMissed = 0;\n";
print "      shootWLP = 0;\n";
print "      shootOLP = 0;\n";
print "      shootHub = 0;\n";
print "      shootField = 0;\n";
print "      rung = 0;\n";
print "      defense = 0;\n";
print "      defended = 0;\n";
print "      fouls = 0;\n";
print "      techfouls = 0;\n";
print "      robot = 0;\n";
print "\n";
print "      function toggle (id) {\n";
print "          var str;\n";
print "          str = \"&nbsp;No\";\n";
print "          if (id == \"taxi\") {\n";
print "              if (taxi == 0) {\n";
print "                  taxi = 1;\n";
print "                  str = \"Yes\";\n";
print "              } else {\n";
print "                  taxi = 0;\n";
print "              }\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + str + \"</font>\";\n";
print "              document.forms[0].taxi.value = taxi;\n";
print "          }\n";
print "          if (id == \"human\") {\n";
print "              if (human == 0) {\n";
print "                  human = 1;\n";
print "                  str = \"Yes\";\n";
print "              } else {\n";
print "                  human = 0;\n";
print "              }\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + str + \"</font>\";\n";
print "              document.forms[0].human.value = human;\n";
print "          }\n";
print "          if (id == \"wlp\") {\n";
print "              if (shootWLP == 0) {\n";
print "                  shootWLP = 1;\n";
print "                  str = \"Yes\";\n";
print "              } else {\n";
print "                  shootWLP = 0;\n";
print "              }\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + str + \"</font>\";\n";
print "              document.forms[0].shootWLP.value = shootWLP;\n";
print "          }\n";
print "          if (id == \"olp\") {\n";
print "              if (shootOLP == 0) {\n";
print "                  shootOLP = 1;\n";
print "                  str = \"Yes\";\n";
print "              } else {\n";
print "                  shootOLP = 0;\n";
print "              }\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + str + \"</font>\";\n";
print "              document.forms[0].shootOLP.value = shootOLP;\n";
print "          }\n";
print "          if (id == \"hub\") {\n";
print "              if (shootHub == 0) {\n";
print "                  shootHub = 1;\n";
print "                  str = \"Yes\";\n";
print "              } else {\n";
print "                  shootHub = 0;\n";
print "              }\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + str + \"</font>\";\n";
print "              document.forms[0].shootHub.value = shootHub;\n";
print "          }\n";
print "          if (id == \"field\") {\n";
print "              if (shootField == 0) {\n";
print "                  shootField = 1;\n";
print "                  str = \"Yes\";\n";
print "              } else {\n";
print "                  shootField = 0;\n";
print "              }\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + str + \"</font>\";\n";
print "              document.forms[0].shootField.value = shootField;\n";
print "          }\n";
print "          if (id == \"lorung\" || id == \"midrung\" || id == \"hirung\" || id == \"trav\") {\n";
print "              loStr   = \"&nbsp;No\";\n";
print "              midStr  = \"&nbsp;No\";\n";
print "              hiStr   = \"&nbsp;No\";\n";
print "              travStr = \"&nbsp;No\";\n";
print "\n";
print "              if (id == \"lorung\") {\n";
print "                  if (rung != 1) {\n";
print "                      rung = 1;\n";
print "                      loStr   = \"Yes\";\n";
print "                      midStr  = \"&nbsp;No\";\n";
print "                      hiStr   = \"&nbsp;No\";\n";
print "                      travStr = \"&nbsp;No\";\n";
print "                  } else {\n";
print "                      rung = 0;\n";
print "                  }\n";
print "              }\n";
print "              if (id == \"midrung\") {\n";
print "                  if (rung != 2) {\n";
print "                      rung = 2;\n";
print "                      loStr   = \"&nbsp;No\";\n";
print "                      midStr  = \"Yes\";\n";
print "                      hiStr   = \"&nbsp;No\";\n";
print "                      travStr = \"&nbsp;No\";\n";
print "                  } else {\n";
print "                      rung = 0;\n";
print "                  }\n";
print "              }\n";
print "              if (id == \"hirung\") {\n";
print "                  if (rung != 3) {\n";
print "                      rung = 3;\n";
print "                      loStr   = \"&nbsp;No\";\n";
print "                      midStr  = \"&nbsp;No\";\n";
print "                      hiStr   = \"Yes\";\n";
print "                      travStr = \"&nbsp;No\";\n";
print "                  } else {\n";
print "                      rung = 0;\n";
print "                  }\n";
print "              }\n";
print "              if (id == \"trav\") {\n";
print "                  if (rung != 4) {\n";
print "                      rung = 4;\n";
print "                      loStr   = \"&nbsp;No\";\n";
print "                      midStr  = \"&nbsp;No\";\n";
print "                      hiStr   = \"&nbsp;No\";\n";
print "                      travStr = \"Yes\";\n";
print "                  } else {\n";
print "                      rung = 0;\n";
print "                  }\n";
print "              }\n";
print "              document.getElementById('lorung').innerHTML = \"<font size=+2>\" + loStr + \"</font>\";\n";
print "              document.getElementById('midrung').innerHTML = \"<font size=+2>\" + midStr + \"</font>\";\n";
print "              document.getElementById('hirung').innerHTML = \"<font size=+2>\" + hiStr + \"</font>\";\n";
print "              document.getElementById('trav').innerHTML = \"<font size=+2>\" + travStr + \"</font>\";\n";
print "              document.forms[0].rung.value = rung;\n";
print "          }\n";
print "      }\n";
print "\n";
print "      function qtoggle (id) {\n";
print "          loStr  = \"&nbsp;No\";\n";
print "          midStr = \"&nbsp;No\";\n";
print "          hiStr  = \"&nbsp;No\";\n";
print "          if (id == 'dlo' || id == 'dmid' || id == 'dhi') {\n";
print "              if (id == 'dlo') {\n";
print "                  if (defense != 1) {\n";
print "                      defense = 1;\n";
print "                      loStr  = \"Yes\";\n";
print "                      midStr = \"&nbsp;No\";\n";
print "                      hiStr  = \"&nbsp;No\";\n";
print "                  } else {\n";
print "                      defense = 0;\n";
print "                  }\n";
print "              }\n";
print "              if (id == 'dmid') {\n";
print "                  if (defense != 2) {\n";
print "                      defense = 2;\n";
print "                      loStr  = \"&nbsp;No\";\n";
print "                      midStr = \"Yes\";\n";
print "                      hiStr  = \"&nbsp;No\";\n";
print "                  } else {\n";
print "                      defense = 0;\n";
print "                  }\n";
print "              }\n";
print "              if (id == 'dhi') {\n";
print "                  if (defense != 3) {\n";
print "                      defense = 3;\n";
print "                      loStr  = \"&nbsp;No\";\n";
print "                      midStr = \"&nbsp;No\";\n";
print "                      hiStr  = \"Yes\";\n";
print "                  } else {\n";
print "                      defense = 0;\n";
print "                  }\n";
print "              }\n";
print "              document.getElementById('dlo').innerHTML = \"<font size=+2>\" + loStr + \"</font>\";\n";
print "              document.getElementById('dmid').innerHTML = \"<font size=+2>\" + midStr + \"</font>\";\n";
print "              document.getElementById('dhi').innerHTML = \"<font size=+2>\" + hiStr + \"</font>\";\n";
print "              document.forms[0].defense.value = defense;\n";
print "              return;\n";
print "          }\n";
print "          \n";
print "          if (id == 'olo' || id == 'omid' || id == 'ohi') {\n";
print "              if (id == 'olo') {\n";
print "                  if (defended != 1) {\n";
print "                      defended = 1;\n";
print "                      loStr  = \"Yes\";\n";
print "                      midStr = \"&nbsp;No\";\n";
print "                      hiStr  = \"&nbsp;No\";\n";
print "                  } else {\n";
print "                      defended = 0;\n";
print "                  }\n";
print "              }\n";
print "              if (id == 'omid') {\n";
print "                  if (defended != 2) {\n";
print "                      defended = 2;\n";
print "                      loStr  = \"&nbsp;No\";\n";
print "                      midStr = \"Yes\";\n";
print "                      hiStr  = \"&nbsp;No\";\n";
print "                  } else {\n";
print "                      defended = 0;\n";
print "                  }\n";
print "              }\n";
print "              if (id == 'ohi') {\n";
print "                  if (defended != 3) {\n";
print "                      defended = 3;\n";
print "                      loStr  = \"&nbsp;No\";\n";
print "                      midStr = \"&nbsp;No\";\n";
print "                      hiStr  = \"Yes\";\n";
print "                  } else {\n";
print "                      defended = 0;\n";
print "                  }\n";
print "              }\n";
print "              document.getElementById('olo').innerHTML = \"<font size=+2>\" + loStr + \"</font>\";\n";
print "              document.getElementById('omid').innerHTML = \"<font size=+2>\" + midStr + \"</font>\";\n";
print "              document.getElementById('ohi').innerHTML = \"<font size=+2>\" + hiStr + \"</font>\";\n";
print "              document.forms[0].defended.value = defended;\n";
print "              return;\n";
print "          }\n";
print "\n";
print "          if (id == 'flo' || id == 'fmid' || id == 'fhi') {\n";
print "              if (id == 'flo') {\n";
print "                  if (fouls != 1) {\n";
print "                      fouls = 1;\n";
print "                      loStr  = \"Yes\";\n";
print "                      midStr = \"&nbsp;No\";\n";
print "                      hiStr  = \"&nbsp;No\";\n";
print "                  } else {\n";
print "                      fouls = 0;\n";
print "                  }\n";
print "              }\n";
print "              if (id == 'fmid') {\n";
print "                  if (fouls != 2) {\n";
print "                      fouls = 2;\n";
print "                      loStr  = \"&nbsp;No\";\n";
print "                      midStr = \"Yes\";\n";
print "                      hiStr  = \"&nbsp;No\";\n";
print "                  } else {\n";
print "                      fouls = 0;\n";
print "                  }\n";
print "              }\n";
print "              if (id == 'fhi') {\n";
print "                  if (fouls != 3) {\n";
print "                      fouls = 3;\n";
print "                      loStr  = \"&nbsp;No\";\n";
print "                      midStr = \"&nbsp;No\";\n";
print "                      hiStr  = \"Yes\";\n";
print "                  } else {\n";
print "                      fouls = 0;\n";
print "                  }\n";
print "              }\n";
print "              document.getElementById('flo').innerHTML = \"<font size=+2>\" + loStr + \"</font>\";\n";
print "              document.getElementById('fmid').innerHTML = \"<font size=+2>\" + midStr + \"</font>\";\n";
print "              document.getElementById('fhi').innerHTML = \"<font size=+2>\" + hiStr + \"</font>\";\n";
print "              document.forms[0].fouls.value = fouls;\n";
print "              return;\n";
print "          }\n";
print "          \n";
print "          if (id == 'tlo' || id == 'tmid' || id == 'thi') {\n";
print "              if (id == 'tlo') {\n";
print "                  if (techfouls != 1) {\n";
print "                      techfouls = 1;\n";
print "                      loStr  = \"Yes\";\n";
print "                      midStr = \"&nbsp;No\";\n";
print "                      hiStr  = \"&nbsp;No\";\n";
print "                  } else {\n";
print "                      techfouls = 0;\n";
print "                  }\n";
print "              }\n";
print "              if (id == 'tmid') {\n";
print "                  if (techfouls != 2) {\n";
print "                      techfouls = 2;\n";
print "                      loStr  = \"&nbsp;No\";\n";
print "                      midStr = \"Yes\";\n";
print "                      hiStr  = \"&nbsp;No\";\n";
print "                  } else {\n";
print "                      techfouls = 0;\n";
print "                  }\n";
print "              }\n";
print "              if (id == 'thi') {\n";
print "                  if (techfouls != 3) {\n";
print "                      techfouls = 3;\n";
print "                      loStr  = \"&nbsp;No\";\n";
print "                      midStr = \"&nbsp;No\";\n";
print "                      hiStr  = \"Yes\";\n";
print "                  } else {\n";
print "                      techfouls = 0;\n";
print "                  }\n";
print "              }\n";
print "              document.getElementById('tlo').innerHTML = \"<font size=+2>\" + loStr + \"</font>\";\n";
print "              document.getElementById('tmid').innerHTML = \"<font size=+2>\" + midStr + \"</font>\";\n";
print "              document.getElementById('thi').innerHTML = \"<font size=+2>\" + hiStr + \"</font>\";\n";
print "              document.forms[0].techfouls.value = techfouls;\n";
print "              return;\n";
print "          }\n";
print "\n";
print "          if (id == 'rlo' || id == 'rmid' || id == 'rhi') {\n";
print "              if (id == 'rlo') {\n";
print "                  if (robot != 1) {\n";
print "                      robot = 1;\n";
print "                      loStr  = \"Yes\";\n";
print "                      midStr = \"&nbsp;No\";\n";
print "                      hiStr  = \"&nbsp;No\";\n";
print "                  } else {\n";
print "                      robot = 0;\n";
print "                  }\n";
print "              }\n";
print "              if (id == 'rmid') {\n";
print "                  if (robot != 2) {\n";
print "                      robot = 2;\n";
print "                      loStr  = \"&nbsp;No\";\n";
print "                      midStr = \"Yes\";\n";
print "                      hiStr  = \"&nbsp;No\";\n";
print "                  } else {\n";
print "                      robot = 0;\n";
print "                  }\n";
print "              }\n";
print "              if (id == 'rhi') {\n";
print "                  if (robot != 3) {\n";
print "                      robot = 3;\n";
print "                      loStr  = \"&nbsp;No\";\n";
print "                      midStr = \"&nbsp;No\";\n";
print "                      hiStr  = \"Yes\";\n";
print "                  } else {\n";
print "                      robot = 0;\n";
print "                  }\n";
print "              }\n";
print "              document.getElementById('rlo').innerHTML = \"<font size=+2>\" + loStr + \"</font>\";\n";
print "              document.getElementById('rmid').innerHTML = \"<font size=+2>\" + midStr + \"</font>\";\n";
print "              document.getElementById('rhi').innerHTML = \"<font size=+2>\" + hiStr + \"</font>\";\n";
print "              document.forms[0].robot.value = robot;\n";
print "              return;\n";
print "          }\n";
print "      }\n";
print "      \n";
print "      function countUp (id) {\n";
print "          if (id == \"alo\") {\n";
print "              autoLoCount++;\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + autoLoCount + \"</font>\";\n";
print "              document.forms[0].autoLoCount.value = autoLoCount;\n";
print "          }\n";
print "          if (id == \"ahi\") {\n";
print "              autoHiCount++;\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + autoHiCount + \"</font>\";\n";
print "              document.forms[0].autoHiCount.value = autoHiCount;\n";
print "          }\n";
print "          if (id == \"abo\") {\n";
print "              autoBounce++;\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + autoBounce + \"</font>\";\n";
print "              document.forms[0].autoBounce.value = autoBounce;\n";
print "          }\n";
print "          if (id == \"ami\") {\n";
print "              autoMissed++;\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + autoMissed + \"</font>\";\n";
print "              document.forms[0].autoMissed.value = autoMissed;\n";
print "          }\n";
print "          if (id == \"lo\") {\n";
print "              teleLoCount++;\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + teleLoCount + \"</font>\";\n";
print "              document.forms[0].teleLoCount.value = teleLoCount;\n";
print "          }\n";
print "          if (id == \"hi\") {\n";
print "              teleHiCount++;\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + teleHiCount + \"</font>\";\n";
print "              document.forms[0].teleHiCount.value = teleHiCount;\n";
print "          }\n";
print "          if (id == \"bo\") {\n";
print "              teleBounce++;\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + teleBounce + \"</font>\";\n";
print "              document.forms[0].teleBounce.value = teleBounce;\n";
print "          }\n";
print "          if (id == \"mi\") {\n";
print "              teleMissed++;\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + teleMissed + \"</font>\";\n";
print "              document.forms[0].teleMissed.value = teleMissed;\n";
print "          }\n";
print "      }\n";
print "\n";
print "      function countDown (id) {\n";
print "          if (id == \"alo\") {\n";
print "              autoLoCount--;\n";
print "              if (autoLoCount < 0) {\n";
print "                  autoLoCount = 0;\n";
print "              }\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + autoLoCount + \"</font>\";\n";
print "              document.forms[0].autoLoCount.value = autoLoCount;\n";
print "          }\n";
print "          if (id == \"ahi\") {\n";
print "              autoHiCount--;\n";
print "              if (autoHiCount < 0) {\n";
print "                  autoHiCount = 0;\n";
print "              }\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + autoHiCount + \"</font>\";\n";
print "              document.forms[0].autoHiCount.value = autoHiCount;\n";
print "          }\n";
print "          if (id == \"abo\") {\n";
print "              autoBounce--;\n";
print "              if (autoBounce < 0) {\n";
print "                  autoBounce = 0;\n";
print "              }\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + autoBounce + \"</font>\";\n";
print "              document.forms[0].autoBounce.value = autoBounce;\n";
print "          }\n";
print "          if (id == \"ami\") {\n";
print "              autoMissed--;\n";
print "              if (autoMissed < 0) {\n";
print "                  autoMissed = 0;\n";
print "              }\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + autoMissed + \"</font>\";\n";
print "              document.forms[0].autoMissed.value = autoMissed;\n";
print "          }\n";
print "          if (id == \"lo\") {\n";
print "              teleLoCount--;\n";
print "              if (teleLoCount < 0) {\n";
print "                  teleLoCount = 0;\n";
print "              }\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + teleLoCount + \"</font>\";\n";
print "              document.forms[0].teleLoCount.value = teleLoCount;\n";
print "          }\n";
print "          if (id == \"hi\") {\n";
print "              teleHiCount--;\n";
print "              if (teleHiCount < 0) {\n";
print "                  teleHiCount = 0;\n";
print "              }\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + teleHiCount + \"</font>\";\n";
print "              document.forms[0].teleHiCount.value = teleHiCount;\n";
print "          }\n";
print "          if (id == \"bo\") {\n";
print "              teleBounce--;\n";
print "              if (teleBounce < 0) {\n";
print "                  teleBounce = 0;\n";
print "              }\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + teleBounce + \"</font>\";\n";
print "              document.forms[0].teleBounce.value = teleBounce;\n";
print "          }\n";
print "          if (id == \"mi\") {\n";
print "              teleMissed--;\n";
print "              if (teleMissed < 0) {\n";
print "                  teleMissed = 0;\n";
print "              }\n";
print "              document.getElementById(id).innerHTML = \"<font size=+2>\" + teleMissed + \"</font>\";\n";
print "              document.forms[0].teleMissed.value = teleMissed;\n";
print "          }\n";
print "      }\n";
print "      </script>\n";
print "    <center>    \n";
print "      <table cellpadding=0 cellspacing=0 $color border=1>\n";
print "        <tr>\n";
print "          <td colspan=4>\n";
print "            <table cellpadding=0 cellspacing=0 $color width=\"100%\" border=1>\n";
print "              <tr>\n";
print "                <th align=\"center\"><font size=+2>Venue: $event</font></th>\n";
print "                <th align=\"center\"><font size=+2>Team : $team</font></th>\n";
print "                <th align=\"center\"><font size=+2>Match : $match</font></th>\n";
print "              </tr>\n";
print "           </table>\n";
print "         </td>\n";
print "       </tr><tr>\n";
print "          <td colspan=4>\n";
print "            <table cellspacing=0 cellpadding=0 width=\"100%\" border=1>\n";
print "              <tr>\n";
print "                <td align=\"center\">\n";
print "                  <table cellpadding=0 cellspacing=0 border=0>\n";
print "                    <tr>\n";
print "                      <td><font size=+2>Taxi Points?&nbsp;</font></td>\n";
print "                      <td>\n";
print "                        <button onclick=\"toggle('taxi')\"><p id=\"taxi\"><font size=+2>&nbsp;No</font></p></button>\n";
print "                      </td>\n";
print "                    </tr>\n";
print "                  </table>\n";
print "                </td>\n";
print "                <th align=\"center\"><font size=+2>Autonomous</font></th>\n";
print "                <td align=\"center\">\n";
print "                  <table cellpadding=0 cellspacing=0 border=0>\n";
print "                    <tr>\n";
print "                      <td><font size=+2>Human Score?&nbsp;</font></td>\n";
print "                      <td>\n";
print "                        <button onclick=\"toggle('human')\"><p id=\"human\"><font size=+2>&nbsp;No</font></p></button>\n";
print "                      </td>\n";
print "                    </tr>\n";
print "                  </table>\n";
print "                </td>\n";
print "              </tr>\n";
print "            </table>\n";
print "          </td>\n";
print "        </tr><tr>\n";
print "          <td>\n";
print "            <table cellpadding=0 cellspacing=0 border=0>\n";
print "              <tr>\n";
print "                <td colspan=2>\n";
print "                  <button onclick=\"countUp('alo')\"><img src=\"/2022/scoutpics/count_up2.png\"></button>\n";
print "                </td>\n";
print "              </tr><tr>\n";
print "                <td align=\"center\"><font size=+2>Lower Hub</font></td>\n";
print "                <td><p id=\"alo\"><font size=+2>0</font></p></td>\n";
print "              </tr><tr>\n";
print "                <td colspan=2 align=\"center\">\n";
print "                  <button onclick=\"countDown('alo')\"><img src=\"/2022/scoutpics/count_down2.png\"></button>\n";
print "                </td>\n";
print "              </tr>\n";
print "            </table>\n";
print "          </td>\n";
print "          <td>\n";
print "            <table cellpadding=0 cellspacing=0 border=0>\n";
print "              <tr>\n";
print "                <td colspan=2>\n";
print "                  <button onclick=\"countUp('abo')\"><img src=\"/2022/scoutpics/count_up2.png\"></button>\n";
print "                </td>\n";
print "              </tr><tr>\n";
print "                <td align=\"center\"><font size=+2>Bounced Out</font></td>\n";
print "                <td><p id=\"abo\"><font size=+2>0</font></p></td>\n";
print "              </tr><tr>\n";
print "                <td colspan=2 align=\"center\">\n";
print "                  <button onclick=\"countDown('abo')\"><img src=\"/2022/scoutpics/count_down2.png\"></button>\n";
print "                </td>\n";
print "              </tr>\n";
print "            </table>\n";
print "          </td>\n";
print "          <td>\n";
print "            <table cellpadding=0 cellspacing=0 border=0>\n";
print "              <tr>\n";
print "                <td colspan=2>\n";
print "                  <button onclick=\"countUp('ami')\"><img src=\"/2022/scoutpics/count_up2.png\"></button>\n";
print "                </td>\n";
print "              </tr><tr>\n";
print "                <td align=\"center\"><font size=+2>Missed Target</font></td>\n";
print "                <td><p id=\"ami\"><font size=+2>0</font></p></td>\n";
print "              </tr><tr>\n";
print "                <td colspan=2 align=\"center\">\n";
print "                  <button onclick=\"countDown('ami')\"><img src=\"/2022/scoutpics/count_down2.png\"></button>\n";
print "                </td>\n";
print "              </tr>\n";
print "            </table>\n";
print "          </td>\n";
print "          <td>\n";
print "            <table cellpadding=0 cellspacing=0 border=0>\n";
print "              <tr>\n";
print "                <td colspan=2>\n";
print "                  <button onclick=\"countUp('ahi')\"><img src=\"/2022/scoutpics/count_up2.png\"></button>\n";
print "                </td>\n";
print "              </tr><tr>\n";
print "                <td align=\"center\"><font size=+2>Upper Hub</font></td>\n";
print "                <td><p id=\"ahi\"><font size=+2>0</font></p></td>\n";
print "              </tr><tr>\n";
print "                <td colspan=2 align=\"center\">\n";
print "                  <button onclick=\"countDown('ahi')\"><img src=\"/2022/scoutpics/count_down2.png\"></button>\n";
print "                </td>\n";
print "              </tr>\n";
print "            </table>\n";
print "          </td>\n";
print "        </tr>\n";
print "      </table>\n";
print "      <p>&nbsp;</p>\n";
print "      <table cellpadding=0 cellspacing=0 border=1>\n";
print "        <tr>\n";
print "          <th colspan=4 align=\"center\"><font size=+4>$team TeleOp</font></th>\n";
print "        </tr><tr>\n";
print "          <td>\n";
print "            <table cellpadding=0 cellspacing=0 border=0>\n";
print "              <tr>\n";
print "                <td colspan=2>\n";
print "                  <button onclick=\"countUp('lo')\"><img src=\"/2022/scoutpics/count_up2.png\"></button>\n";
print "                </td>\n";
print "              </tr><tr>\n";
print "                <td align=\"center\"><font size=+2>Lower Hub</font></td>\n";
print "                <td><p id=\"lo\"><font size=+2>0</font></p></td>\n";
print "              </tr><tr>\n";
print "                <td colspan=2 align=\"center\">\n";
print "                  <button onclick=\"countDown('lo')\"><img src=\"/2022/scoutpics/count_down2.png\"></button>\n";
print "                </td>\n";
print "              </tr>\n";
print "            </table>\n";
print "          </td>\n";
print "          <td>\n";
print "            <table cellpadding=0 cellspacing=0 border=0>\n";
print "              <tr>\n";
print "                <td colspan=2>\n";
print "                  <button onclick=\"countUp('bo')\"><img src=\"/2022/scoutpics/count_up2.png\"></button>\n";
print "                </td>\n";
print "              </tr><tr>\n";
print "                <td align=\"center\"><font size=+2>Bounced Out</font></td>\n";
print "                <td><p id=\"bo\"><font size=+2>0</font></p></td>\n";
print "              </tr><tr>\n";
print "                <td colspan=2 align=\"center\">\n";
print "                  <button onclick=\"countDown('bo')\"><img src=\"/2022/scoutpics/count_down2.png\"></button>\n";
print "                </td>\n";
print "              </tr>\n";
print "            </table>\n";
print "          </td>\n";
print "          <td>\n";
print "            <table cellpadding=0 cellspacing=0 border=0>\n";
print "              <tr>\n";
print "                <td colspan=2>\n";
print "                  <button onclick=\"countUp('mi')\"><img src=\"/2022/scoutpics/count_up2.png\"></button>\n";
print "                </td>\n";
print "              </tr><tr>\n";
print "                <td align=\"center\"><font size=+2>Missed Target</font></td>\n";
print "                <td><p id=\"mi\"><font size=+2>0</font></p></td>\n";
print "              </tr><tr>\n";
print "                <td colspan=2 align=\"center\">\n";
print "                  <button onclick=\"countDown('mi')\"><img src=\"/2022/scoutpics/count_down2.png\"></button>\n";
print "                </td>\n";
print "              </tr>\n";
print "            </table>\n";
print "          </td>\n";
print "          <td>\n";
print "            <table cellpadding=0 cellspacing=0 border=0>\n";
print "              <tr>\n";
print "                <td colspan=2>\n";
print "                  <button onclick=\"countUp('hi')\"><img src=\"/2022/scoutpics/count_up2.png\"></button>\n";
print "                </td>\n";
print "              </tr><tr>\n";
print "                <td align=\"center\"><font size=+2>Upper Hub</font></td>\n";
print "                <td><p id=\"hi\"><font size=+2>0</font></p></td>\n";
print "              </tr><tr>\n";
print "                <td colspan=2 align=\"center\">\n";
print "                  <button onclick=\"countDown('hi')\"><img src=\"/2022/scoutpics/count_down2.png\"></button>\n";
print "                </td>\n";
print "              </tr>\n";
print "            </table>\n";
print "          </td>\n";
print "        </tr>\n";
print "      </table>\n";
print "      <table cellpadding=0 cellspacing=0 border=1>\n";
print "        <tr>\n";
print "          <td>\n";
print "            <p><font size=+2>&nbsp;Robot Shot From:&nbsp;&nbsp;</font></p>\n";
print "          </td>\n";
print "          <td>\n";
print "            <table cellpadding=0 cellspacing=0 border=1>\n";
print "              <tr><td align=center>\n";
print "                  <font size=+2>&nbsp;Against&nbsp;<br>&nbsp;Hub:&nbsp;</font>\n";
print "                </td><td>\n";
print "                  <button onclick=\"toggle('hub')\"><p id=\"hub\"><font size=+2>&nbsp;No</font></p></button>\n";
print "              </td></tr>\n";
print "            </table>\n";
print "          </td>\n";
print "          <td>\n";
print "            <table cellpadding=0 cellspacing=0 border=1>\n";
print "              <tr><td align=center>\n";
print "                  <font size=+2>&nbsp;Spots&nbsp;<br>&nbsp;in Field:&nbsp;</font>\n";
print "                </td><td>\n";
print "                  <button onclick=\"toggle('field')\"><p id=\"field\"><font size=+2>&nbsp;No</font></p></button>\n";
print "              </td></tr>\n";
print "            </table>\n";
print "          </td>\n";
print "          <td>\n";
print "            <table cellpadding=0 cellspacing=0 border=1>\n";
print "              <tr>\n";
print "                <td colspan=4 align=\"center\">\n";
print "                  <font size=+2>Against Launch Pad</font>\n";
print "                </td>\n";
print "              </tr><tr>\n";
print "                <td>\n";
print "                  <p><font size=+2>&nbsp;&nbsp;&nbsp;Outer:&nbsp;&nbsp;</font></p>\n";
print "                </td><td>\n";
print "                  <button onclick=\"toggle('olp')\"><p id=\"olp\"><font size=+2>&nbsp;No</font></p></button>\n";
print "                </td>\n";
print "                <td>\n";
print "                  <p><font size=+2>&nbsp;&nbsp;&nbsp;Wall:&nbsp;&nbsp;</font></p>\n";
print "                </td><td>\n";
print "                  <button onclick=\"toggle('wlp')\"><p id=\"wlp\"><font size=+2>&nbsp;No</font></p></button>\n";
print "                </td>\n";
print "              </tr>\n";
print "            </table>\n";
print "          </td>\n";
print "        </tr>\n";
print "      </table>\n";
print "      <p>&nbsp;</p>\n";
print "      <table cellpadding=0 cellspacing=0 $color border=1>\n";
print "        <tr>\n";
print "          <th colspan=5 align=\"center\"><font size=+4>End Game</font></th>\n";
print "        </tr><tr>\n";
print "          <td>\n";
print "            <p><font size=+2>&nbsp;Robot Hung From:&nbsp;&nbsp;</font></p>\n";
print "          </td>\n";
print "          <td>\n";
print "            <table cellpadding=0 cellspacing=0 border=1>\n";
print "              <tr><td>\n";
print "                  <p><font size=+2>&nbsp;Low:&nbsp;</font></p>\n";
print "                </td><td>\n";
print "                  <button onclick=\"toggle('lorung')\"><p id=\"lorung\"><font size=+2>&nbsp;No</font></p></button>\n";
print "              </td></tr>\n";
print "            </table>\n";
print "          </td>\n";
print "          <td>\n";
print "            <table cellpadding=0 cellspacing=0 border=1>\n";
print "              <tr><td>\n";
print "                  <p><font size=+2>&nbsp;Middle:&nbsp;</font></p>\n";
print "                </td><td>\n";
print "                  <button onclick=\"toggle('midrung')\"><p id=\"midrung\"><font size=+2>&nbsp;No</font></p></button>\n";
print "              </td></tr>\n";
print "            </table>\n";
print "          </td>\n";
print "          <td>\n";
print "            <table cellpadding=0 cellspacing=0 border=1>\n";
print "              <tr><td>\n";
print "                  <p><font size=+2>&nbsp;High:&nbsp;</font></p>\n";
print "                </td><td>\n";
print "                  <button onclick=\"toggle('hirung')\"><p id=\"hirung\"><font size=+2>&nbsp;No</font></p></button>\n";
print "              </td></tr>\n";
print "            </table>\n";
print "          </td>\n";
print "          <td>\n";
print "            <table cellpadding=0 cellspacing=0 border=1>\n";
print "              <tr><td>\n";
print "                  <p><font size=+2>&nbsp;Traversal:&nbsp;</font></p>\n";
print "                </td><td>\n";
print "                  <button onclick=\"toggle('trav')\"><p id=\"trav\"><font size=+2>&nbsp;No</font></p></button>\n";
print "              </td></tr>\n";
print "            </table>\n";
print "          </td>\n";
print "        </tr>\n";
print "      </table>\n";
print "      <p>&nbsp;</p>\n";
print "      <table cellpadding=0 cellspacing=0 border=1>\n";
print "        <tr>\n";
print "          <th colspan=3 align=\"center\"><font size=+4>Post-Match Robot Review</font></th>\n";
print "        </tr><tr>\n";
print "          <th colspan=3 $color><hr></th>\n";
print "        </tr><tr>\n";
print "          <th colspan=3 align=\"center\"><font size=+2>Did $team play defense?</font></th>\n";
print "        </tr><tr>\n";
print "          <th>\n";
print "            <font size=+2>Good Defense</font>\n";
print "          </th><td>\n";
print "            <button onclick=\"qtoggle('dhi')\"><p id=\"dhi\"><font size=+2>&nbsp;No</font></p></button>\n";
print "          </td><td align=center>\n";
print "            <font size=+2><b>Not many</b> game pieces scored<br> by opponent during defense</font>\n";
print "          </td>\n";
print "        </tr><tr>\n";
print "          <th>\n";
print "            <font size=+2>Average Defense</font>\n";
print "          </th><td>\n";
print "            <button onclick=\"qtoggle('dmid')\"><p id=\"dmid\"><font size=+2>&nbsp;No</font></p></button>\n";
print "          </td><td align=center>\n";
print "            <font size=+2>Opponent was still able<br> to score <b>some</b> game pieces</font>\n";
print "          </td>\n";
print "        </tr><tr>\n";
print "          <th>\n";
print "            <font size=+2>Below Average Defense</font>\n";
print "          </th><td>\n";
print "            <button onclick=\"qtoggle('dlo')\"><p id=\"dlo\"><font size=+2>&nbsp;No</font></p></button>\n";
print "          </td><td align=center>\n";
print "            <font size=+2>Opponent was still able to<br>&nbsp;&nbsp;score game pieces <b>without delay</b>&nbsp;&nbsp;</font>\n";
print "          </td>\n";
print "        </tr><tr>\n";
print "          <th colspan=3 $color><hr></th>\n";
print "        </tr><tr>\n";
print "          <th colspan=3 align=\"center\"><font size=+2>Was $team defended?</font></th>\n";
print "        </tr><tr>\n";
print "          <th>\n";
print "            <font size=+2>Good Against Defense</font>\n";
print "          </th><td>\n";
print "            <button onclick=\"qtoggle('ohi')\"><p id=\"ohi\"><font size=+2>&nbsp;No</font></p></button>\n";
print "          </td><td align=center>\n";
print "            <font size=+2>Defended but still scored game<br>&nbsp;pieces with <b>little to no delay</b>&nbsp;</font>\n";
print "          </td>\n";
print "        </tr><tr>\n";
print "          <th>\n";
print "            <font size=+2>Average Against Defense</font>\n";
print "          </th><td>\n";
print "            <button onclick=\"qtoggle('omid')\"><p id=\"omid\"><font size=+2>&nbsp;No</font></p></button>\n";
print "          </td><td align=center>\n";
print "            <font size=+2>Defended but still able to score<br> <b>some</b> game pieces with delay</font>\n";
print "          </td>\n";
print "        </tr><tr>\n";
print "          <th>\n";
print "            <font size=+2>Affected by Defense</font>\n";
print "          </th><td>\n";
print "            <button onclick=\"qtoggle('olo')\"><p id=\"olo\"><font size=+2>&nbsp;No</font></p></button>\n";
print "          </td><td align=center>\n";
print "            <font size=+2>Good defense <b>really affected</b><br> robot performance</font>\n";
print "          </td>\n";
print "        </tr><tr>\n";
print "          <th colspan=3 $color><hr></th>\n";
print "        </tr><tr>\n";
print "          <th colspan=3 align=\"center\"><font size=+2>Did $team receive any fouls?</font></th>\n";
print "        </tr><tr>\n";
print "          <td colspan=3>\n";
print "            <table cellpadding=0 cellspacing=0 width=\"100%\" border=1>\n";
print "              <tr>\n";
print "                <td>\n";
print "                  <button onclick=\"qtoggle('flo')\"><p id=\"flo\"><font size=+2>&nbsp;No</font></p></button>\n";
print "                </td><th>\n";
print "                  <font size=+2>1 foul</font>\n";
print "                </th><th>\n";
print "                  <font size=+2>1 tech foul</font>\n";
print "                </th><td>\n";
print "                  <button onclick=\"qtoggle('tlo')\"><p id=\"tlo\"><font size=+2>&nbsp;No</font></p></button>\n";
print "                </td>\n";
print "              </tr><tr>\n";
print "                <td>\n";
print "                  <button onclick=\"qtoggle('fmid')\"><p id=\"fmid\"><font size=+2>&nbsp;No</font></p></button>\n";
print "                </td><th>\n";
print "                  <font size=+2>2 fouls</font>\n";
print "                </th><th>\n";
print "                  <font size=+2>2 tech fouls</font>\n";
print "                </th><td>\n";
print "                  <button onclick=\"qtoggle('tmid')\"><p id=\"tmid\"><font size=+2>&nbsp;No</font></p></button>\n";
print "                </td>\n";
print "              </tr><tr>\n";
print "                <td>\n";
print "                  <button onclick=\"qtoggle('fhi')\"><p id=\"fhi\"><font size=+2>&nbsp;No</font></p></button>\n";
print "                </td><th>\n";
print "                  <font size=+2>3 or more fouls</font>\n";
print "                </th><th>\n";
print "                  <font size=+2>3 or more tech fouls</font>\n";
print "                </th><td>\n";
print "                  <button onclick=\"qtoggle('thi')\"><p id=\"thi\"><font size=+2>&nbsp;No</font></p></button>\n";
print "                </td>\n";
print "              </tr>\n";
print "            </table>\n";
print "          </td>\n";
print "        </tr><tr>\n";
print "          <th colspan=3 $color><hr></th>\n";
print "        </tr><tr>\n";
print "          <th colspan=3 align=\"center\"><font size=+2>Is this a good robot?</font></th>\n";
print "        </tr><tr>\n";
print "          <th>\n";
print "            <font size=+2>Very good robot</font>\n";
print "          </th><td>\n";
print "            <button onclick=\"qtoggle('rhi')\"><p id=\"rhi\"><font size=+2>&nbsp;No</font></p></button>\n";
print "          </td><td align=center>\n";
print "            <font size=+2>Could be an alliance captain</font>\n";
print "          </td>\n";
print "        </tr><tr>\n";
print "          <th>\n";
print "            <font size=+2>Decent robot</font>\n";
print "          </th><td>\n";
print "            <button onclick=\"qtoggle('rmid')\"><p id=\"rmid\"><font size=+2>&nbsp;No</font></p></button>\n";
print "          </td><td align=center>\n";
print "            <font size=+2>a productive and useful robot</font>\n";
print "          </td>\n";
print "        </tr><tr>\n";
print "          <th>\n";
print "            <font size=+2>Struggled to be effective</font>\n";
print "          </th><td>\n";
print "            <button onclick=\"qtoggle('rlo')\"><p id=\"rlo\"><font size=+2>&nbsp;No</font></p></button>\n";
print "          </td><td align=center>\n";
print "            <font size=+2>Maybe good at one thing,<br> but bad at others</font>\n";
print "          </td>\n";
print "        </tr><tr>\n";
print "          <th colspan=3 $color><hr></th>\n";
print "        </tr><tr>\n";
print "          <th colspan=3 align=\"center\">\n";
print "            <p><font size=+2>Scouter Name:</font><input type=\"text\" name=\"scouter\" form=\"wrapup\"></p>\n";
print "            <p><font size=+2>Comments:</font><textarea name=\"comments\" form=\"wrapup\" cols=\"60\" rows=\"5\"></textarea></p>\n";
print "          </th>\n";
print "        </tr>\n";
print "      </table>\n";
print "\n";
print "      <form action=\"/react2.cgi\" id=\"wrapup\" enctype=\"text/plain\">\n";
print "        <input type=\"hidden\" name=\"game\" value=\"$game\">\n";
print "        <input type=\"hidden\" name=\"team\" value=\"$team\">\n";
print "        <input type=\"hidden\" name=\"autoLoCount\" id=\"alo\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"autoHiCount\" id=\"ahi\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"autoBounce\" id=\"abo\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"autoMissed\" id=\"ami\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"teleLoCount\" id=\"lo\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"teleHiCount\" id=\"hi\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"teleMissed\" id=\"mi\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"teleBounce\" id=\"bo\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"taxi\" id=\"taxi\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"human\" id=\"human\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"shootHub\" id=\"hub\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"shootField\" id=\"field\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"shootOLP\" id=\"olp\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"shootWLP\" id=\"wlp\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"rung\" id=\"rung\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"defense\" id=\"defense\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"defended\" id=\"defended\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"fouls\" id=\"fouls\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"techfouls\" id=\"techfouls\" value=\"0\">\n";
print "        <input type=\"hidden\" name=\"robot\" id=\"robot\" value=\"0\">\n";
print "        <input type=\"image\" src=\"/2022/scoutpics/save_button.png\" width=\"100\" height=\"50\">\n";
print "      </form>\n";
print "    </center>\n";
print "</body></html>\n";
